language: generic
os: linux
matrix:
  include:
    - os: linux
      env: COMPILER_NAME=clang CXX=clang++-5.0 CC=clang-5.0
      addons:
        apt:
          packages:
            - clang-5.0
            - gcc-7.0
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-5.0

script: make
