sudo: false
language: generic
os: linux
matrix:
  include:
    - os: linux
      env: COMPILER_NAME=clang CXX=clang++-5.0 CC=clang-5.0
      addons:
        apt:
          packages:
#            - clang-5.0
#            - g++-7
            - python3.6
            - python3.6-pip
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-5.0
            - deadsnakes

install:
  - export PATH="`pwd`/build:${PATH}"
  - wget https://github.com/ninja-build/ninja/releases/download/v1.7.2/ninja-linux.zip && unzip -q ninja-linux.zip -d build
  - pip3.6 install meson

script:
  - meson builddir
  - ninja -C builddir
  - ninja -C builddir test
