language: generic
os: linux
matrix:
  include:
    - os: linux
      env: COMPILER_NAME=clang CXX=clang++-6.0 CC=clang-6.0
      addons:
        apt:
          packages:
            - clang-6.0
          sources:
            - llvm-toolchain-trusty-6.0

script: make
